Bug fixes: 1. Image messages sending fixed. Wrong GGMessaging API method was used to send image messages.     * The interactor was also refactored so it requires the captured image's path instead of working against ImageRepository's getPath method. 2. UserLocation messages are not added to the MessageRepository.
teamagam/GimelGimel pull request #119
Opened 2016-11-30 14:47 UTC by BarAgam

Bug fixes:
1. Image messages sending fixed. Wrong GGMessaging API method was used to send image messages.
    * The interactor was also refactored so it requires the captured image's path instead of working against ImageRepository's getPath method.
2. UserLocation messages are not added to the MessageRepository.

2016-11-30 14:47 UTC, review-ninja commented
<a href="https://app.review.ninja/teamagam/GimelGimel/pull/119" target="_blank"><img src="https://app.review.ninja/52010471/pull/119/badge" alt="ReviewNinja"/>

2016-11-30 20:35 UTC, teamagam1 requested changes

2016-11-30 20:35 UTC, teamagam1 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/view/SendImageFragment.java
> +    private static final String CAPTURED_IMAGE_PATH_KEY = "captured_image";
why have you moved the key string from the view model to the view?

2016-11-30 20:35 UTC, teamagam1 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/view/SendImageFragment.java
> +        return ImageUtils.getTempImageUri(getContext());
ImageUtils is in data module. Are you sure this is a good idea to call it directly?

2016-11-30 20:35 UTC, teamagam1 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/entity/contents/ImageMetadataData.java
> +    private String mLocalUrl;
use key word **transient**

2016-11-30 20:35 UTC, teamagam1 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/contents/ImageMetadata.java
> +    public void setLocalUrl(String localUrl) {
I dont like the set option. 
Also you never used it...

2016-12-01 09:18 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/view/SendImageFragment.java
> +    private static final String CAPTURED_IMAGE_PATH_KEY = "captured_image";
because the fragment uses it

2016-12-01 09:18 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/view/SendImageFragment.java
> +        return ImageUtils.getTempImageUri(getContext());
yes.
Is it problematic?

2016-12-01 09:19 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/entity/contents/ImageMetadataData.java
> +    private String mLocalUrl;
cool

2016-12-01 09:21 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/contents/ImageMetadata.java
> +    public void setLocalUrl(String localUrl) {
k

2016-12-01 13:43 UTC, merged