task/sensor_panel/refactoring_interactors
teamagam/GimelGimel pull request #127
Opened 2016-12-13 14:27 UTC by BarAgam

Refactoring interactors to share code when subscribing and unsubscribing from multiple (or single) observable.
Most of the sync interactors have been refactored, with the exception of few "bad" interactors that needs to change in the future.
Do interactors have not been refactored, but a new base class that supports the above refactoring have been implemented - BaseDataInteractor.
AbsInteractor, SyncInteractor and DoInteractor needs to be deleted when these changes will be adopted completely.

2016-12-13 14:27 UTC, review-ninja commented
<a href="https://app.review.ninja/teamagam/GimelGimel/pull/127" target="_blank"><img src="https://app.review.ninja/52010471/pull/127/badge" alt="ReviewNinja"/>

2016-12-20 10:39 UTC, teamagam1 requested changes

2016-12-20 10:39 UTC, teamagam1 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/base/interactors/DisplaySubscriptionRequest.java
> +        public <T> DisplaySubscriptionRequest create(Observable<T> observable,
add generics to the return type

2016-12-20 10:39 UTC, teamagam1 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/base/interactors/DisplaySubscriptionRequest.java
> +            return new DisplaySubscriptionRequest(mThreadExecutor, mPostExecutionThread, observable,
add generics to new, also to the second method

2016-12-20 10:39 UTC, teamagam1 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/base/interactors/DataSubscriptionRequest.java
> +        public BaseInteractor.SubscriptionRequest create(Observable observable) {
generify this method

2016-12-20 10:39 UTC, teamagam1 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/base/interactors/BaseInteractor.java
> +    public BaseInteractor() {
can be protected

2016-12-20 10:39 UTC, teamagam1 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/base/interactors/BaseDisplayInteractor.java
> +    protected abstract Iterable<SubscriptionRequest> buildSubscriptionRequests(
I'm not sure about this Iterable thing. Every interactor should return Collection.toSingleton?

2016-12-21 15:43 UTC, closed without merging