Feature/panel/swipe
teamagam/GimelGimel pull request #131
Opened 2016-12-15 12:00 UTC by agamgil

2016-12-15 12:00 UTC, review-ninja commented
<a href="https://app.review.ninja/teamagam/GimelGimel/pull/131" target="_blank"><img src="https://app.review.ninja/52010471/pull/131/badge" alt="ReviewNinja"/>

2016-12-19 09:41 UTC, BarAgam requested changes

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/common/base/adapters/BottomPanelPagerAdapter.java
> +/**
Redundant comment

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/common/base/adapters/BottomPanelPagerAdapter.java
> +    String[] mTitles;
Access modifiers missing

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/common/base/adapters/BottomPanelPagerAdapter.java
> +        // Generate title based on item position
Redundant comment

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivity.java
> +    //{getString(R.string.PanelTitleSensors), getString(R.string.PanelTitleMessages)};
?

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivity.java
> +        android.support.v4.app.FragmentManager fragmentManager = getSupportFragmentManager();
android.support.v4.app prefix is redundant

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +/**
Redundant comment

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivity.java
> +    private void initButtomPanel() {
Bottom *

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    private Activity mActivity;
Field not used

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    PagerSlidingTabStrip tabsStrip;
Injected fields are not consistently named

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    ViewPager mButtomViewPager;
Bottom*

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    public void Init() {
init*

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +        BottomPanelPagerAdapter mPageAdapter =
local variable named as a field

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +         //Attach the view pager to the tab strip
I'd extract that line into a new method with an informative name if you'd like to keep comment information.
If this comment is not important enough for that, then it's not important enough to stay there.

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +/**
Redundant comment

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public void setArguments (String[] titles, int numOfTitles) {
If the class cannot exist without these parameters, then it should ask for them at the constructor.

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public void setArguments (String[] titles, int numOfTitles) {
There's no point in asking for an array and it's length.
One can simply ask the array for it's length when required.

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public interface PanelDisplayer {
Seems like an empty interface.

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public String[] getTitles() {
Is anyone using that?

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/res/layout/activity_main_content.xml
> +        <android.support.v4.view.ViewPager xmlns:android="http://schemas.android.com/apk/res/android"
There's no need to declare android namespace in the xml again,

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/res/layout/activity_main_content.xml
> +            android:id="@+id/tabs"
The identifier should be more informative in such a way that will tell the developer which tabs exactly this id is referring to (main_activity_bottom_panel_tabs perhaps?)

2016-12-19 09:41 UTC, BarAgam commented on app/src/main/res/layout/activity_main_content.xml
> +            android:id="@+id/buttom_swiping_panel"
bottom*

2016-12-21 09:45 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    PagerSlidingTabStrip tabsStrip;
what do you mean?

2016-12-21 09:45 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    ViewPager mButtomViewPager;
done

2016-12-21 09:45 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +/**
done

2016-12-21 09:45 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivity.java
> +        android.support.v4.app.FragmentManager fragmentManager = getSupportFragmentManager();
done

2016-12-21 09:45 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivity.java
> +    private void initButtomPanel() {
done

2016-12-21 09:46 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivity.java
> +    //{getString(R.string.PanelTitleSensors), getString(R.string.PanelTitleMessages)};
done

2016-12-21 09:46 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/common/base/adapters/BottomPanelPagerAdapter.java
> +        // Generate title based on item position
done

2016-12-21 09:46 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/common/base/adapters/BottomPanelPagerAdapter.java
> +    String[] mTitles;
done

2016-12-21 09:46 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/common/base/adapters/BottomPanelPagerAdapter.java
> +/**
done

2016-12-21 09:48 UTC, gRaytan commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    private Activity mActivity;
done

2016-12-21 09:48 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    public void Init() {
done

2016-12-21 09:49 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +        BottomPanelPagerAdapter mPageAdapter =
done

2016-12-21 09:49 UTC, gRaytan commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +/**
done

2016-12-21 09:52 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public void setArguments (String[] titles, int numOfTitles) {
i had a problem with dagger, and thats what yoni suggested. any other ideas?

2016-12-21 09:52 UTC, gRaytan commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public void setArguments (String[] titles, int numOfTitles) {
righe, done

2016-12-21 09:53 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public String[] getTitles() {
At first, i thought we will use. i left it for future expansion

2016-12-21 11:19 UTC, gRaytan commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public interface PanelDisplayer {
It currently an empy interace. left it for future expansion

2016-12-21 11:20 UTC, gRaytan commented on app/src/main/res/layout/activity_main_content.xml
> +            android:id="@+id/tabs"
ok, done

2016-12-21 11:22 UTC, agamgil commented on app/src/main/res/layout/activity_main_content.xml
> +        <android.support.v4.view.ViewPager xmlns:android="http://schemas.android.com/apk/res/android"
done

2016-12-21 11:23 UTC, agamgil commented on app/src/main/res/layout/activity_main_content.xml
> +            android:id="@+id/buttom_swiping_panel"
done

2016-12-21 11:24 UTC, agamgil commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +         //Attach the view pager to the tab strip
not sure i am agree, anyone feletd tht comment

2016-12-21 15:23 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    PagerSlidingTabStrip tabsStrip;
That it's not prefixed with an 'm' like the rest of the injected/binded fields

2016-12-21 15:23 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/view/MainActivityPanel.java
> +    PagerSlidingTabStrip tabsStrip;
That it's not prefixed with an 'm' like the rest of the injected/binded fields

2016-12-21 15:26 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/mainActivity/viewmodel/PanelViewModel.java
> +    public void setArguments (String[] titles, int numOfTitles) {
Yeah. The solution to this situation is creating a factory that will inject this class' dependencies and ask for the required parameters. 
AutoFactory helps with that and generates the boilerplate code for you.
I can help you with that.

2016-12-22 11:41 UTC, merged