task/bugs_fix/validate_non_space
teamagam/GimelGimel pull request #139
Opened 2017-01-03 08:18 UTC by teamagam5

now geo/text message can be sent only if valid (indicated by the send button's enabled/disabled state)

2017-01-04 13:39 UTC, teamagam3 requested changes
General comment:
The observable in those dialogs uses weird indicator (BR.inputNotValid),
Change it to normal indicator (Like the EditText id) if possible

2017-01-04 13:39 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
> +    private boolean isText(String mText) {
Duplicate code.
We talked about utility class, haven't you implemented it yet?

2017-01-12 08:57 UTC, teamagam3 requested changes

2017-01-12 08:57 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/view/SendGeographicMessageDialog.java
> +public class SendGeographicMessageDialog extends BaseBindingDialogFragment implements SendGeoMessageViewModel.IViewDismisser {
Again, the order of the methods isn't good here

2017-01-12 08:57 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
> +    protected void executeInteractor() {
Methods order

2017-01-12 08:57 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendMessageViewModel.java
> +    protected void executeInteractor() {
Methods order

2017-01-12 08:57 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendSimpleMessageViewModel.java
> +public class SendSimpleMessageViewModel extends SendMessageViewModel {
You should delete this class, you've created it because of the name.
You have the functionality you want in the base class, so use it instead.

2017-01-16 13:03 UTC, teamagam5 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendSimpleMessageViewModel.java
> +public class SendSimpleMessageViewModel extends SendMessageViewModel {
Decided after consulting Bar to keep it that way

2017-01-16 13:03 UTC, merged