task/alerts/alert_signal
teamagam/GimelGimel pull request #158
Opened 2017-01-30 18:35 UTC by BarAgam

Notifying user when a new alerts is received.
App's toolbar is animating from its original color to red (repeatedly) and it's (the toolbar's) title is changing to alert.
The toolbar status is being restored after clicking on it.

2017-01-31 17:00 UTC, teamagam3 requested changes

2017-01-31 17:00 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/Alerts/view/BubbleAlertsSubcomponent.java
> +        mToolbar = (Toolbar) activity.findViewById(R.id.main_toolbar);
ButterKnife can be used here

2017-01-31 17:00 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/Alerts/view/BubbleAlertsSubcomponent.java
> +    private class MyTitleSetter implements BubbleAlertsViewModel.TitleSetter {
Change the name of the title setter

2017-01-31 17:00 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/Alerts/view/BubbleAlertsSubcomponent.java
> +    private class MyToolbarAnimator implements BubbleAlertsViewModel.ToolbarAnimator {
Changed the name of the class

2017-01-31 17:00 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/alerts/repository/AlertsDataRepository.java
> +        mReplayRepository = ReplayRepository.createReplayCount(1);
I understand why you changed this, but what if someone needs to get all of the alerts?

2017-01-31 17:00 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/alerts/repository/InformedAlertsDataRepository.java
> +        mLatestInformedDate = new Date(0);
Is there a Date.minValue() or something similar?

2017-01-31 17:00 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/config/Constants.java
> +    public static final String MESSAGING_SERVER_URL = "http://ggmessaging-dev1.herokuapp.com";
Revert changes

2017-01-31 17:00 UTC, teamagam3 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/alerts/UpdateLatestInformedAlertTimeInteractor.java
> +public class UpdateLatestInformedAlertTimeInteractor extends BaseDataInteractor {
Don't we need a simpler class for this functionality?
It's not real "subsription request", we just want to update the InformedAlertsRepository.

Maybe I just don't understand the real meaning of this kind of class. Isn't it  just for long streams like messages streams?

2017-02-01 09:54 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/Alerts/view/BubbleAlertsSubcomponent.java
> +        mToolbar = (Toolbar) activity.findViewById(R.id.main_toolbar);
Unfortunately I couldn't make it happen here.

2017-02-01 10:03 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/alerts/repository/AlertsDataRepository.java
> +        mReplayRepository = ReplayRepository.createReplayCount(1);
That's right.

2017-02-01 10:14 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/alerts/repository/InformedAlertsDataRepository.java
> +        mLatestInformedDate = new Date(0);
Nope.

2017-02-01 10:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/alerts/UpdateLatestInformedAlertTimeInteractor.java
> +public class UpdateLatestInformedAlertTimeInteractor extends BaseDataInteractor {
Basically we're using interactors for everything kind of action we want to make on our domain.
It's a good for several reasons, like uniformly manipulating domain from app and allows for logic to be implemented independently for each "use-case" (=interactors).

2017-02-01 14:12 UTC, teamagam3 approved these changes

2017-02-01 14:12 UTC, merged