RxJava2!!!
teamagam/GimelGimel pull request #305
Opened 2017-06-07 15:36 UTC by teamagam5

Good luck to the CRer :)

2017-06-12 12:16 UTC, teamagam3 requested changes

2017-06-12 12:16 UTC, teamagam3 commented on app/build.gradle
> +    exclude 'META-INF/rxjava.properties'
Do we need it?
I saw it just for backward compatibility with rxjava 1

2017-06-12 12:16 UTC, teamagam3 commented on app/src/main/java/com/teamagam/gimelgimel/app/settings/dialogs/SetUsernameAlertDialogBuilder.java
> +        sLogger.e("Dialog's positive button was clicked but callback threw an exception:\n"
Use `System.lineSeparator()` instead of `\n`

2017-06-12 12:16 UTC, teamagam3 commented on app/src/test/java/com/teamagam/gimelgimel/app/integration/interactors/DisplayVectorLayerInteractorTest.java
> +    return Schedulers.trampoline();
Trampoline is little different, it still uses the current thread to run the code, but schedule every code block, like it's in different thread.
Maybe that's the reason you get race condition more frequently.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/base/repository/SubjectRepository.java
> +  private final Subject<T> mSerializedReplaySubject;
Why did you remove the serialized subject support?
I think we need it because of we call it from different threads.
`SerializedSubject` is no longer "create-able", you can init it with `.toSerialized` method.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/common/OkHttpClientFactory.java
> +    return (hostname, session) -> {
I like the old code here, but it's your choice.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/location/repository/LocationDataRepository.java
> +  private final Subject<LocationSample> mSubject;
You can use the SubjectRepository here.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/base/repository/SubjectRepository.java
> +  private final Subject<T> mSerializedReplaySubject;
I missed the old code, it's fine.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/poller/MessageLongPoller.java
> +        .toFlowable(BackpressureStrategy.BUFFER)
Nice, but I think we should solve this problem from its root.
The `GGMessaingAPI` should return a `Flowable` and not `Observable`.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/poller/MessageLongPoller.java
> +        .toObservable();
You do nothing by casting back to `Observable`.
It should remain `Flowable` in the entire processing stage.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/rest/adapter/factory/RxErrorHandlingCallAdapterFactory.java
> +      return ((Observable) mWrapped.adapt(call)).onErrorResumeNext(
If Retrofit supports `Flowable`, you should cast this object to it.

2017-06-12 12:16 UTC, teamagam3 commented on data/src/main/java/com/teamagam/gimelgimel/data/notifications/MessageNotificationsSubject.java
> +  private Subject<MessageNotification> mSubject;
Use `SubjectRepistory`.

2017-06-12 12:16 UTC, teamagam3 commented on dependencies.gradle
> +      retrofitRxAdapter      : 'com.squareup.retrofit2:adapter-rxjava2:2.2.0',
Extracting retrofit version to variable would be nice.

2017-06-12 12:16 UTC, teamagam3 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/location/SendSelfLocationsInteractor.java
> +            .toObservable()
Same as said in `MessageLongPoller` class.

2017-06-13 07:53 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/common/OkHttpClientFactory.java
> +    return (hostname, session) -> {
Sorry. I like the new one. In addition, the IDE is to my side. :stuck_out_tongue:

2017-06-13 07:53 UTC, teamagam5 commented on app/build.gradle
> +    exclude 'META-INF/rxjava.properties'
I know I also hoped it won't be needed, but somehow the rx1 version is yet not totally gone. Not sure for the reason, but this change fixes the problem...

2017-06-13 07:53 UTC, teamagam5 commented on app/src/main/java/com/teamagam/gimelgimel/app/settings/dialogs/SetUsernameAlertDialogBuilder.java
> +        sLogger.e("Dialog's positive button was clicked but callback threw an exception:\n"
done

2017-06-13 07:54 UTC, teamagam5 commented on app/src/test/java/com/teamagam/gimelgimel/app/integration/interactors/DisplayVectorLayerInteractorTest.java
> +    return Schedulers.trampoline();
I know, but it's a test so it's not supposed to influence the app's performance.
I understand the cons of trampoline but it's the best solution exists in rx2 as for my understanding.

2017-06-13 07:55 UTC, teamagam5 commented on app/src/test/java/com/teamagam/gimelgimel/app/integration/interactors/DisplayVectorLayerInteractorTest.java
> +    return Schedulers.trampoline();
Also it's the recommended replacment

2017-06-13 07:55 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/base/repository/SubjectRepository.java
> +  private final Subject<T> mSerializedReplaySubject;
:+1:

2017-06-13 07:55 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/common/OkHttpClientFactory.java
> +    return (hostname, session) -> {
Sorry. I like the new one. In addition, the IDE is to my side. :stuck_out_tongue:

2017-06-13 07:56 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/location/repository/LocationDataRepository.java
> +  private final Subject<LocationSample> mSubject;
IIRC *you* already did, in your task. Should I replace it too or just count on yours...?

2017-06-13 08:17 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/poller/MessageLongPoller.java
> +        .toFlowable(BackpressureStrategy.BUFFER)
I don't agree, before moving to rx2 The `GGMessaingAPI` returned a simple `Observable` and only by the end of THIS method you used the backpressure operator (which returns a `Flowable`-like `Observable`). So IMO I can still use the `toFlowable` operator, but I agree that in the rest of the processing it should remain a `Flowable`.

2017-06-13 08:18 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/poller/MessageLongPoller.java
> +        .toObservable();
see above

2017-06-13 08:20 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/rest/adapter/factory/RxErrorHandlingCallAdapterFactory.java
> +      return ((Observable) mWrapped.adapt(call)).onErrorResumeNext(
I need explanasion

2017-06-13 08:20 UTC, teamagam5 commented on data/src/main/java/com/teamagam/gimelgimel/data/notifications/MessageNotificationsSubject.java
> +  private Subject<MessageNotification> mSubject;
See above (somewhere up)

2017-06-13 08:23 UTC, teamagam5 commented on dependencies.gradle
> +      retrofitRxAdapter      : 'com.squareup.retrofit2:adapter-rxjava2:2.2.0',
pls explain.
and if a hotfix is released for one of the components?

2017-06-13 08:24 UTC, teamagam5 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/location/SendSelfLocationsInteractor.java
> +            .toObservable()
I think that here the logical filtering is sufficient for handling a backpressure. Don't u agree?

2017-06-13 14:54 UTC, merged