Task/messages queue/handle sending failure
teamagam/GimelGimel pull request #356
Opened 2017-08-01 12:46 UTC by teamagam7

2017-08-02 07:16 UTC, BarAgam requested changes
Talk with me if you got any questions :>

2017-08-02 07:16 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +      MessageSender messageSender,
Just ask dagger to build OutgoingMessageQueueSenderImpl for you

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/NetworkStateReceiverListenerImpl.java
> +  public NetworkStateReceiverListenerImpl(Context context) {
It's a convention thing -  we usually call data package classes different - 
DataNetwrokStateReceiverListener or NetwrokStateReceiverDataListener

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/NetworkStateReceiverListenerImpl.java
> +    context.registerReceiver(this,
Just mentioning it again - 
This constructor doesn't just initialize its members but actually invokes some logic.
I'd rather see this be done in a start method instead.

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/NetworkStateReceiverListenerImpl.java
> +    static int getConnectivityStatusString(Context context) {
it says get string but returns int >.<

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/NetworkStateReceiverListenerImpl.java
> +  public void networkStateChange(Boolean isOffline) {
This should be renamed to changeNetworkState

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +public class OutGoingMessageQueueSenderImpl implements OutGoingMessageQueueSender {
again, by convention  we name this class DataOutGoingMessageQueueSender

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +  private RetryWithDelay mRetryStrategy;
Declared and initialized but not used 😕

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +    mChatMessageObserver.onComplete();
shouldn't you use dispose instead?

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +  private void startGettingMessages() {
startSendingMessages ? this method doesn't get anything

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +      e.printStackTrace();
Use only the logger to report exceptions

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +      dispose();
Redundant.

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public static final int MESSAGE_SEND_DELAY_AMOUNT = 2000;
As we said, thread sleep shouldn't be used anyways.
But, if you declare a time constant (or any other "unit of measurement" constant), embed the units in its name.
I.e - DISTANCE_METERS, TIME_MILLIS, TIME_DAYS, etc...

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  private SubjectRepository<ChatMessage> mChatMessageSubject;
Unfortunately, this isn't actually a subject, but a wrapper class for subjects (the name SubjectRepository isn't good, we made a mistake - I'll change that).

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +    mChatMessageSubject.add(mMessagesQueue.peek());
I think it'll be more readable (and perhaps even a bit more efficient) to add chatMessage instead of querying the queue for its top message.

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public ChatMessage getMessage() {
The name of this method isn't informative.
When used it'll always look something like this - outgoingMessageQueue.getMessage
What message exactly does it get? the first one? the last one ? a random message?
you implement it by returning the first-in-line message.
If that's the required behavior, change the name to reflect that

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public synchronized void removeMessage() {
like the last comment.... this should be renamed - 
removeTopMessage?
pop?

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public void addAllMessagesToObservable() {
This method isn't annotated with the override annotation.
We talked about it in person, it (the method) shouldn't exist.

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  private void delaySending() {
SHAME 👸

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +  private Boolean mNetworkState;
boolean ?

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +public class NetworkStateRepositoryImpl implements NetworkStateRepository {
Again, by convention, we call this NetworkStateDataRepository

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/map/SelectMessageByEntityInteractor.java
> +  private final com.teamagam.gimelgimel.domain.map.repository.SelectedEntityRepository
Why were these changes made?

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/map/SelectMessageByEntityInteractor.java
> +  private final com.teamagam.gimelgimel.domain.map.repository.SelectedEntityRepository
I'm talking about all the changes in this file

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +  public boolean doesHaveInternetConnetion() {
isConnected?

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/NetworkStateReceiverListener.java
> +  void networkStateChange(Boolean isOnline);
never used.
It means you're using the wrong observable to start/stop the sending process

2017-08-02 07:16 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +  public void setInternetConnetion(boolean networkStates) {
typo in connection

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SelectEntityByMessageInteractor.java
> +@com.google.auto.factory.AutoFactory
????????????

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SelectEntityByMessageInteractor.java
> +          com.teamagam.gimelgimel.domain.messages.repository.ObjectMessageMapper entityMessageMapper,
?????????????????????????

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SendMessageOnAvailableNetworkInteractor.java
> +        factory.create(mNetworkStateReceiverListener.getObservable(),
You should use the network-state-repository here instead...

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/OutGoingMessagesQueue.java
> +  ChatMessage getMessage();
As I wrote before, rename this method

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/OutGoingMessagesQueue.java
> +  void addAllMessagesToObservable();
And this should be removed.

2017-08-02 07:16 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/repository/NetworkStateRepository.java
> +public interface NetworkStateRepository {
you'll probably need to add getObservable() here....

2017-08-02 13:24 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public void addAllMessagesToObservable() {
done

2017-08-02 13:25 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public synchronized void removeMessage() {
done

2017-08-02 13:26 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public ChatMessage getMessage() {
done

2017-08-02 13:31 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +    mChatMessageSubject.add(mMessagesQueue.peek());
done

2017-08-02 13:33 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +      dispose();
done

2017-08-02 13:34 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +    mChatMessageObserver.onComplete();
done

2017-08-02 13:53 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +  private void startGettingMessages() {
done

2017-08-02 13:53 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +  private RetryWithDelay mRetryStrategy;
done

2017-08-02 13:54 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessageQueueSenderImpl.java
> +public class OutGoingMessageQueueSenderImpl implements OutGoingMessageQueueSender {
done

2017-08-02 14:41 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/NetworkStateReceiverListenerImpl.java
> +    context.registerReceiver(this,
done

2017-08-02 14:41 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/NetworkStateReceiverListenerImpl.java
> +  public NetworkStateReceiverListenerImpl(Context context) {
done

2017-08-02 19:16 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/OutGoingMessagesDataQueue.java
> +  public static final int MESSAGE_SEND_DELAY_AMOUNT = 2000;
done

2017-08-02 19:17 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +public class NetworkStateRepositoryImpl implements NetworkStateRepository {
done

2017-08-02 19:17 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +  private Boolean mNetworkState;
done

2017-08-02 19:18 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +  public boolean doesHaveInternetConnetion() {
done

2017-08-02 19:20 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/NetworkStateRepositoryImpl.java
> +  public void setInternetConnetion(boolean networkStates) {
done

2017-08-03 01:18 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/map/SelectMessageByEntityInteractor.java
> +  private final com.teamagam.gimelgimel.domain.map.repository.SelectedEntityRepository
done

2017-08-03 01:21 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/NetworkStateReceiverListener.java
> +  void networkStateChange(Boolean isOnline);
done, the arguments names were different but he still called that method

2017-08-03 01:24 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SelectEntityByMessageInteractor.java
> +@com.google.auto.factory.AutoFactory
done

2017-08-03 01:32 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SelectEntityByMessageInteractor.java
> +          com.teamagam.gimelgimel.domain.messages.repository.ObjectMessageMapper entityMessageMapper,
I cant find that line in my code

2017-08-03 01:44 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SendMessageOnAvailableNetworkInteractor.java
> +        factory.create(mNetworkStateReceiverListener.getObservable(),
* I'm using it

2017-08-03 01:44 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/OutGoingMessagesQueue.java
> +  ChatMessage getMessage();
done

2017-08-03 01:44 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/OutGoingMessagesQueue.java
> +  void addAllMessagesToObservable();
done

2017-08-03 01:57 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/repository/NetworkStateRepository.java
> +public interface NetworkStateRepository {
why, what the point? I already have class the supply me an observable for network state changes the repository only exist to hold a Boolean field which represent the network state at the time that he being called

2017-08-09 12:33 UTC, closed without merging