Outgoing Messaging queue persisted.
teamagam/GimelGimel pull request #364
Opened 2017-08-08 15:24 UTC by teamagam7

2017-08-09 12:32 UTC, BarAgam requested changes
Remove code dups of all the OutGoingChatMessage and ChatMessage mappers

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +    return new DataOutGoingMessagesQueue(outGoingMessagesDao, messagesEntityMapper);
Ask dagger to create DataOutGoing.... by itself.

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
>      return new MessageSenderData(cloudMessagesSource, serverDataMapper);
ask dagger to build MessageSenderData by itself.
Also, rename MessageSenderData to DataMessageSender.

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +    return new DataNetworkStateRepository(networkStateReceiverListener);
Again...
Ask dagger to build the desired outcome object by itself

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +    return new DataNetworkStateReceiverListener(context);
Again, ask dagger to build the desired outcome object by itself

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +  DataOutGoingMessageQueueSender provideDataOutGoingMessageQueueSender(MessageNotifications messageNotification,
Again, ask dagger to build the desired outcome object by itself

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
> +        mQueueGeoMessageForSendingInteractorFactory.create(mText, pointGeometry, getSymbol());
redundant spaces after this line

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
>          new com.teamagam.gimelgimel.domain.map.entities.geometries.PointGeometry(
Remove fully qualified class name

2017-08-09 12:32 UTC, BarAgam commented on app/src/main/res/layout/fragment_send_geometry.xml
> +        type="com.teamagam.gimelgimel.app.map.viewModel.SendGeometryViewModel"
That's bad.
You moved the class from where it's suppose to be.
Probably a rebase issue.
You should compare you branch with develop, and see where these classes should reside.

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataNetworkStateReceiverListener.java
> +import static com.teamagam.gimelgimel.data.message.repository.DataNetworkStateReceiverListener.NetworkUtil.getConnectivityStatusString;
this is redundant, just prefix calls with NetworkUtil

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataNetworkStateReceiverListener.java
> +  public void networkStateChange(Boolean isOffline) {
The whole use of booleans to represent the network state is bad.
You have switched in your implementation from isOnline to isOffline.
This inconsistency is bug-prone.
There's an object in our project called ConnectivityStatus that can be use here.
All your DatanetworkStateRepository can reuse the existing ConnectivityStatusRepository.

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessageQueueSender.java
> +  private class SentMessagesObserver extends ResourceObserver<OutGoingChatMessage> {
You can extend from ErrorLoggingObserver.
It'll reduce the code size and will log errors for you.

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessagesQueue.java
> +    mMessagesQueue = convertEntitiesIterable(mOutGoingMessagesDao.getMessagesByOutGoingId());
Constructor is calling DB opertaions.
This is weird since it's not expected that creating an object will cause DB access.
This whole thing can be resolved (we talked about it in person) if you wouldn't use the in-memory Queue object at all, and just work directly against the DB.

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessagesQueue.java
> +  public void switchTopMessageToQueueStart() {
I'd reconsider the existence of this method inside this repository. It looks to me like an operation that should be implemented elsewhere since it's not a basic repository operation.
And in any case, I'd rename it to moveTopToBottom

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/AppDatabase.java
> +  public abstract OutGoingMessagesDao outgoingMessageDao();
spacing

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/entities/OutGoingChatMessageEntity.java
> +@Entity(inheritSuperIndices = true, tableName = "out_going_messages", indices = {
inheritSuperIndices is no use here since this class has no superclass

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/MessagesEntityMapper.java
> +  private Style convertStyleEntityToStyle(GeoFeatureEntity.Style style) {
??????????????????????
Seems like a new private method without any usages.

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingChatMessageFeaturesToEntityFeatures.java
> +  private OutGoingChatMessageEntity mChatMessageEntity;
rename to mOutGoingChatMessageEntity

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingMessagesEntityMapper.java
> +    OutGoingChatMessageEntity outGoingChatMessageEntity = createOutGoingChatMessageEntity(message);
inline

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/DataNetworkStateRepository.java
> +  private class NetworkStateUpdatesObserver extends ResourceObserver<Boolean> {
Use ErrorLoggingObserver.

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> +  List<OutGoingChatMessageEntity> getMessagesByOutGoingId();
You wouldn't need this method if you use the DB at the repository instead of in-memory.
You'll need getFirst() method.

2017-08-09 12:32 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("tudu bom", mDao.getMessagesByOutGoingId().size() == 1);
assertThat(mDao.getMessagesByOutGoingId, hasSize(1))

2017-08-09 12:32 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("tudu bom", mDao.getMessagesByOutGoingId().get(0).outGoingMessageId == 3);
....

2017-08-09 12:32 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("tudu bom", mDao.getMessagesByOutGoingId().size() == 0);
...

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/map/SelectMessageByEntityInteractor.java
> +  protected final SelectEntityInteractorFactory mSelectEntityInteractorFactory;
reformat it back to it's previous state.

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/QueueImageMessageForSendingInteractor.java
>      ChatMessage chatMessage = new ChatMessage(null, senderId, null,
build an outgoing message...

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/ChatMessage.java
> +  public ChatMessage(OutGoingChatMessage outGoingChatMessage, String messageId) {
not used

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/QueueTextMessageForSendingInteractor.java
>      return new ChatMessage(null, senderId, null, new TextFeature(mText.trim()));
Create outgoing message

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SendMessageOnAvailableNetworkInteractor.java
> +    mNetworkStateRepository.startGettingNetworksStatesUpdates();
We've talked about it already.
This line should be executed from it's own interactor - startNetworkUpdatesInteractor (or something...)

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/OutGoingMessagesQueue.java
> +  void switchTopMessageToQueueStart();
rename

2017-08-09 12:32 UTC, BarAgam commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/poller/PolledMessagesProcessor.java
> +  public synchronized void process(ChatMessage message) {
I think you left it here unintentionally

2017-08-09 12:32 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingChatMessageFeaturesToEntityFeatures.java
> +public class OutGoingChatMessageFeaturesToEntityFeatures implements MessageFeatureVisitor {
Code dups with the ChatMessage equivalent

2017-08-09 13:05 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +    return new DataOutGoingMessagesQueue(outGoingMessagesDao, messagesEntityMapper);
done

2017-08-09 13:06 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
>      return new MessageSenderData(cloudMessagesSource, serverDataMapper);
done

2017-08-09 13:06 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +    return new DataNetworkStateRepository(networkStateReceiverListener);
done

2017-08-09 13:06 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +    return new DataNetworkStateReceiverListener(context);
done

2017-08-09 13:06 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/injectors/modules/MessageModule.java
> +  DataOutGoingMessageQueueSender provideDataOutGoingMessageQueueSender(MessageNotifications messageNotification,
done

2017-08-09 13:08 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
>          new com.teamagam.gimelgimel.domain.map.entities.geometries.PointGeometry(
done

2017-08-09 13:10 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
> +        mQueueGeoMessageForSendingInteractorFactory.create(mText, pointGeometry, getSymbol());
done

2017-08-09 13:15 UTC, teamagam7 commented on app/src/main/res/layout/fragment_send_geometry.xml
> +        type="com.teamagam.gimelgimel.app.map.viewModel.SendGeometryViewModel"
done.

2017-08-09 13:16 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataNetworkStateReceiverListener.java
> +import static com.teamagam.gimelgimel.data.message.repository.DataNetworkStateReceiverListener.NetworkUtil.getConnectivityStatusString;
done

2017-08-09 13:45 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessageQueueSender.java
> +  private class SentMessagesObserver extends ResourceObserver<OutGoingChatMessage> {
done

2017-08-09 15:05 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessagesQueue.java
> +  public void switchTopMessageToQueueStart() {
done

2017-08-10 07:58 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessagesQueue.java
> +    mMessagesQueue = convertEntitiesIterable(mOutGoingMessagesDao.getMessagesByOutGoingId());
done

2017-08-10 08:00 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/AppDatabase.java
> +  public abstract OutGoingMessagesDao outgoingMessageDao();
done

2017-08-10 08:01 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/entities/OutGoingChatMessageEntity.java
> +@Entity(inheritSuperIndices = true, tableName = "out_going_messages", indices = {
no

2017-08-10 08:02 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/entities/OutGoingChatMessageEntity.java
> +@Entity(inheritSuperIndices = true, tableName = "out_going_messages", indices = {
done

2017-08-10 08:04 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/MessagesEntityMapper.java
> +  private Style convertStyleEntityToStyle(GeoFeatureEntity.Style style) {
done

2017-08-10 12:11 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingChatMessageFeaturesToEntityFeatures.java
> +public class OutGoingChatMessageFeaturesToEntityFeatures implements MessageFeatureVisitor {
done

2017-08-10 12:28 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingChatMessageFeaturesToEntityFeatures.java
> +  private OutGoingChatMessageEntity mChatMessageEntity;
done

2017-08-10 12:30 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingMessagesEntityMapper.java
> +    OutGoingChatMessageEntity outGoingChatMessageEntity = createOutGoingChatMessageEntity(message);
done

2017-08-10 12:33 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/user/repository/DataNetworkStateRepository.java
> +  private class NetworkStateUpdatesObserver extends ResourceObserver<Boolean> {
done

2017-08-10 12:36 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> +  List<OutGoingChatMessageEntity> getMessagesByOutGoingId();
done,we talked about this in person.

2017-08-10 12:43 UTC, teamagam7 commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("tudu bom", mDao.getMessagesByOutGoingId().size() == 1);
done

2017-08-10 12:50 UTC, teamagam7 commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("tudu bom", mDao.getMessagesByOutGoingId().size() == 0);
done

2017-08-10 12:58 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/QueueImageMessageForSendingInteractor.java
>      ChatMessage chatMessage = new ChatMessage(null, senderId, null,
done

2017-08-10 13:02 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/map/SelectMessageByEntityInteractor.java
> +  protected final SelectEntityInteractorFactory mSelectEntityInteractorFactory;
done

2017-08-10 13:02 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/ChatMessage.java
> +  public ChatMessage(OutGoingChatMessage outGoingChatMessage, String messageId) {
done

2017-08-10 13:04 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/QueueTextMessageForSendingInteractor.java
>      return new ChatMessage(null, senderId, null, new TextFeature(mText.trim()));
done

2017-08-10 13:11 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/entity/OutGoingMessagesQueue.java
> +  void switchTopMessageToQueueStart();
done

2017-08-10 13:12 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/poller/PolledMessagesProcessor.java
> +  public synchronized void process(ChatMessage message) {
done.

2017-08-10 14:13 UTC, teamagam7 commented on domain/src/main/java/com/teamagam/gimelgimel/domain/messages/SendMessageOnAvailableNetworkInteractor.java
> +    mNetworkStateRepository.startGettingNetworksStatesUpdates();
done

2017-08-13 13:00 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> -  @Query("DELETE FROM out_going_messages")
that nuke is needed and should be used with the other nukes to clean to database (for development uses)

2017-08-13 13:00 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> +  @Query("SELECT * FROM out_going_messages ORDER BY out_going_id DESC LIMIT 1")
You can use the min keyword to improve performance (possibly) and readability

2017-08-13 13:00 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessagesQueue.java
>    private Queue<OutGoingChatMessage> convertEntitiesIterable(List<OutGoingChatMessageEntity> outGoingChatMessageEntityList) {
You can use Lists.transform to instead of this method

2017-08-13 13:00 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/FeaturesToEntityFeaturesUtilities.java
> +public class FeaturesToEntityFeaturesUtilities {
Use the name mapper to increase readability.
 FeatureToEntityMapper for instance

2017-08-13 13:00 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/MessagesEntityMapper.java
> +      features.add(mMessageFeatureEntityMapper.createFeature(entity.text, entity.geoFeatureEntity,
extract compound parameter to a method / variable

2017-08-13 13:00 UTC, BarAgam commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingMessagesEntityMapper.java
> +      features.add(mMessageFeatureEntityMapper.createFeature(entity.text, entity.geoFeatureEntity,
extract compound parameter

2017-08-13 13:00 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
>    }
You're missing the @After method that clears the database

2017-08-13 13:00 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("Error: id is: " + mDao.getTopMessage().outGoingMessageId,
Use the proper assertion tools.
`assertThat(mDao.geTopMessage().outGoingMessageId, is(4))`

2017-08-13 13:00 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +  public void getLastMessageTest() {
Doesn't test getLast. rename,

2017-08-13 13:00 UTC, BarAgam commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
>    }
You can add isolated tests for getTopMessage that you'll implement with the MIN keyword.

2017-08-13 13:00 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/SendGeoMessageViewModel.java
>          new com.teamagam.gimelgimel.domain.map.entities.geometries.PointGeometry(
You got another one just below it.

2017-08-15 06:20 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> -  @Query("DELETE FROM out_going_messages")
?

2017-08-15 06:21 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> -  @Query("DELETE FROM out_going_messages")
done

2017-08-15 07:16 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/DataOutGoingMessagesQueue.java
>    private Queue<OutGoingChatMessage> convertEntitiesIterable(List<OutGoingChatMessageEntity> outGoingChatMessageEntityList) {
done

2017-08-15 07:23 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDao.java
> +  @Query("SELECT * FROM out_going_messages ORDER BY out_going_id DESC LIMIT 1")
done

2017-08-15 07:42 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/FeaturesToEntityFeaturesUtilities.java
> +public class FeaturesToEntityFeaturesUtilities {
done

2017-08-15 07:48 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/MessagesEntityMapper.java
> +      features.add(mMessageFeatureEntityMapper.createFeature(entity.text, entity.geoFeatureEntity,
done

2017-08-15 07:50 UTC, teamagam7 commented on data/src/main/java/com/teamagam/gimelgimel/data/message/repository/cache/room/mappers/OutGoingMessagesEntityMapper.java
> +      features.add(mMessageFeatureEntityMapper.createFeature(entity.text, entity.geoFeatureEntity,
done

2017-08-15 07:51 UTC, teamagam7 commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
>    }
done

2017-08-15 07:52 UTC, teamagam7 commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +  public void getLastMessageTest() {
done

2017-08-15 07:54 UTC, teamagam7 commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
> +    assertTrue("Error: id is: " + mDao.getTopMessage().outGoingMessageId,
done

2017-08-15 08:01 UTC, teamagam7 commented on data/src/test/java/com/teamagam/gimelgimel/data/message/repository/cache/room/dao/OutGoingMessagesDaoTest.java
>    }
done

2017-08-15 11:51 UTC, merged