Task/messages search/ui
teamagam/GimelGimel pull request #373
Opened 2017-08-20 07:49 UTC by teamagam7

2017-08-20 09:47 UTC, BarAgam requested changes

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onNextResultSearchCLick() {
typo in CLick

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onNextResultSearchCLick() {
and it should be click*ed*

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onPreviousResultSearchCLick() {
typo in CLick + should be Clicked

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onEditSearchBoxResultCLick(CharSequence text) {
typo in CLick + should be Clicked

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +    return mIsSearchBoxVisible;
called fabVisible, returns boxVisible ?

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  private void hideSearchButton() {
This doesn't necessarily hide, it just toggles the current state.
It's a little tricky to understand from this code alone that changing the BOX boolean flag is effecting the box AND the FAB.

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +    if (mIsSearchBoxVisible) {
This simple boolean flip can be done with:
`bool = !bool`

2017-08-20 09:47 UTC, BarAgam commented on app/src/main/res/values/strings.xml
> +  <string name="search">Search</string>
Don't forget to add an Hebrew string as-well....

2017-08-22 07:13 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +    return mIsSearchBoxVisible;
done

2017-08-22 07:19 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onNextResultSearchCLick() {
done

2017-08-22 07:23 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onPreviousResultSearchCLick() {
done

2017-08-22 07:25 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  public void onEditSearchBoxResultCLick(CharSequence text) {
done

2017-08-22 07:27 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +  private void hideSearchButton() {
done

2017-08-22 07:27 UTC, teamagam7 commented on app/src/main/java/com/teamagam/gimelgimel/app/message/viewModel/MessagesViewModel.java
> +    if (mIsSearchBoxVisible) {
done

2017-08-22 07:30 UTC, teamagam7 commented on app/src/main/res/values/strings.xml
> +  <string name="search">Search</string>
done

2017-08-23 06:40 UTC, merged